# Generated by Django 5.0 on 2024-01-04 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsumerServiceProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                (
                    "consumer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_providers",
                        to="myapp.consumer",
                    ),
                ),
                (
                    "service_provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consumers",
                        to="myapp.serviceprovider",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="consumerserviceprovider",
            constraint=models.UniqueConstraint(
                fields=("consumer", "service_provider"),
                name="consumer_service_provider",
            ),
        ),
    ]
